apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secret
  namespace: default
type: Opaque
stringData:
  port: "4002"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/payday_payment"
  AUTH_URL: http://auth-service:4001
  PAYMENT_URL: http://payment-service:4002
