apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
  namespace: default
type: Opaque
stringData:
  port: "4001"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/payday_auth"
  JWT_SECRET: "payday_super_secret_key"
  AUTH_URL: http://auth-service:4001
  PAYMENT_URL: http://payment-service:4002
